# -*- coding: utf-8 -*-
"""Project 116.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WGF3OZOWuQHsLOtNlxJJ6HqoIlng8zIZ
"""

from google.colab import files
filesToUpload = files.upload()

import pandas as pd
import plotly.express as px
import csv

df = pd.read_csv("data.csv")
TOEFLList = df["TOEFL Score"].tolist()
GREList = df["GRE Score"].tolist()

fig = px.scatter(x = TOEFLList, y = GREList)
fig.show()

from google.colab import files
filesToUpload = files.upload()

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import csv

df = pd.read_csv("data.csv")
TOEFLList = df["TOEFL Score"].tolist()
GREList = df["GRE Score"].tolist()

COAList = df["Chance of admit"].tolist()

color = []

for data in COAList:
  if data ==1:
    color.append("green")
  else:
    color.append("red")

fig = go.Figure(data = go.Scatter(
    x = TOEFLList,
    y = GREList,
    mode = "markers",
    marker = dict(
        color = color
    )
))
fig.show()